name: msm-Build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm8150
          - mh2lm
          - betalm
          - nabu
          - vayu-huaxing
          - vayu-tianma
          - cepheus
          - hotdog
          - guacamole
          - guacamoleb
          # sdm845
          - fajita
          - beryllium-ebbg
          - beryllium-tianma
          - polaris
          - perseus
          # sm7325
          - mona
          - lisa
          # msm8998
          - cheeseburger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/winehq.gpg
          sudo apt-get update
          sudo apt-get -y install libsdl2-dev:i386  # 安装32位SDL2开发库
          sudo apt-get -y install \
            build-essential \
            uuid-dev \
            clang \
            llvm \
            iasl \
            nasm \
            gcc-aarch64-linux-gnu \
            abootimg \
            python3-distutils \
            python3-pil \
            python3-git \
            gettext \
            libgcc-s1:i386 \
            libstdc++6:i386 \
            winehq-stable

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: ./*.img