name: msm-Build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm8150
          - mh2lm
          - betalm
          - nabu
          - vayu-huaxing
          - vayu-tianma
          - cepheus
          - hotdog
          - guacamole
          - guacamoleb
          # sdm845
          - fajita
          - beryllium-ebbg
          - beryllium-tianma
          - polaris
          - perseus
          # sm7325
          - mona
          - lisa
          # msm8998
          - cheeseburger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          # 1. 添加32位架构支持
          sudo dpkg --add-architecture i386

          # 2. 启用所有必要仓库
          sudo add-apt-repository -y multiverse
          sudo apt update

          # 3. 安装基础32位库
          sudo apt install -y libgcc-s1:i386 libstdc++6:i386

          # 4. 安装SDL2和构建工具链
          sudo apt install -y libsdl2-dev:i386 \
            build-essential \
            uuid-dev \
            clang \
            llvm \
            iasl \
            nasm \
            gcc-aarch64-linux-gnu \
            abootimg \
            python3-distutils \
            python3-pil \
            python3-git \
            gettext

          # 5. 安装WineHQ（先修复密钥问题）
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/winehq.gpg
          sudo apt install -y winehq-stable

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: ./*.img