name: msm-Build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm8150
          - mh2lm
          - betalm
          - nabu
          - vayu-huaxing
          - vayu-tianma
          - cepheus
          - hotdog
          - guacamole
          - guacamoleb
          # sdm845
          - fajita
          - beryllium-ebbg
          - beryllium-tianma
          - polaris
          - perseus
          # sm7325
          - mona
          - lisa
          # msm8998
          - cheeseburger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          # 1. 添加32位架构支持
          sudo dpkg --add-architecture i386

          # 2. 启用 multiverse 和 universe 仓库
          sudo add-apt-repository -y multiverse
          sudo add-apt-repository -y universe

          # 3. 更新包列表
          sudo apt update

          # 4. 安装基础32位库
          sudo apt install -y libgcc-s1:i386 libstdc++6:i386

          # 5. 安装 SDL2 和构建工具链
          sudo apt install -y libsdl2-dev:i386 \
            build-essential \
            uuid-dev \
            clang \
            llvm \
            iasl \
            nasm \
            gcc-aarch64-linux-gnu \
            abootimg \
            gettext

          # 6. 安装 Python 依赖（替换 python3-pil 为 python3-pillow）
          sudo apt install -y python3.12-distutils python3-pillow python3-git

          # 7. 安装 WineHQ（先修复密钥问题）
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/winehq.gpg
          sudo apt install -y winehq-stable

          # 8. 修复可能的依赖问题
          sudo apt --fix-broken install -y

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: ./*.img